name: Viral Metagenomics CI

on: [push, pull_request]  

jobs:

  complete_workflow:
    runs-on: ubuntu-latest
    env:
      NXF_ANSI_LOG: 0
      NXF_VER: 20.01.0
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - name:  Run workflow
        run: |
          nextflow run main.nf --manifest test_data/manifest.csv --output_folder output --output_prefix output --human_genome_tar test_data/human_mitochondrial_genome.fasta.tar.gz -profile testing -with-docker ubuntu:20.04
